include:
  - project: 'infinity-economics/iep-docker'
    file: '/gitlab/ci/docker-ci-cd.yml'

download-artifacts:
  stage: prepare
  script:
    - ls -alt
  needs:
    - project: infinity-economics/iep-wallet-ui
      ref: ${CI_COMMIT_REF_NAME}
      job: docker-build
      artifacts: true
  before_script:
      - ls -alt

docker-build:
  stage: build
  before_script:
      - apk add --update --no-cache git curl bash
      - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
      - export WALLET_UI_BUILD_FILE=/builds/infinity-economics/iep-node/build/iep-wallet-ui.zip
      - ls -alt
  artifacts:
    paths:
      - build/iep-node.zip
      - src/main/resources/system.properties
      - conf/mainnet.properties
      - conf/testnet.properties
      - conf/custom.properties
      - conf/templates/installer.properties
      - src/main/resources/log4j2.xml
      - CHANGELOG-@{iep.xin.version}.md
      - LICENSE.txt

trigger-iep-node-installer:
  stage: publish
  needs: ["docker-build"]
  trigger: infinity-economics/iep-node-installer