variables:
  DOCKER_SERVICE_NAME: "node-1"

download-artifacts:
  stage: prepare
  script:
    - ls -alt build
  needs:
    - project: infinity-economics/iep-wallet-ui
      ref: ${CI_COMMIT_REF_NAME}
      job: docker-build
      artifacts: true
  artifacts:
    paths:
      - build/

include:
  - project: 'infinity-economics/iep-docker'
    file: '/gitlab/ci/docker-ci-cd.yml'

docker-build:
  before_script:
      - apk add --update --no-cache git curl bash
      - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
      - docker info
      - export WALLET_UI_BUILD_FILE=/builds/infinity-economics/iep-node/build/iep-wallet-ui.zip
      - pwd
      - ls -lat /builds/infinity-economics/iep-node/build/


trigger-iep-node-installer:
  stage: publish
  needs: ["docker-build"]
  trigger: infinity-economics/iep-node-installer