variables:
  DOCKER_SERVICE_NAME: "node-1"

download-artifacts:
  stage: prepare
  script:
    - pwd
    - ls -alt build
  needs:
    - project: infinity-economics/iep-wallet-ui
      job: docker-build
      ref: develop
      artifacts: true

include:
  - project: 'infinity-economics/iep-docker'
    file: '/gitlab/ci/docker-ci-cd.yml'

docker-build:
  before_script:
      - apk add --update --no-cache git curl bash
      - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
      - docker info
      - echo "------> before_script"
      - export WALLET_UI_BUILD_FILE=/builds/infinity-economics/iep-node/build/iep-wallet-ui.zip
      - pwd
      - ls -lat /builds/infinity-economics
      - ls -lat /builds/infinity-economics/iep-node
      - ls -lat /builds/infinity-economics/iep-node/build