include:
  - project: 'infinity-economics/iep-docker'
    file: '/gitlab/ci/docker-ci-cd.yml'

download-artifacts:
  stage: prepare
  script:
    - ls -alt build
  needs:
    - project: infinity-economics/iep-wallet-ui
      ref: ${CI_COMMIT_REF_NAME}
      job: docker-build
      artifacts: true
  artifacts:
    paths:
      - build/

docker-build:
  stage: build
  before_script:
      - apk add --update --no-cache git curl bash
      - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
      - export WALLET_UI_BUILD_FILE=/builds/infinity-economics/iep-node/build/iep-wallet-ui.zip
      - ls -alt
  artifacts:
    paths:
      - build/iep-node.tar
#      - build/iep-node.zip
prepare-iep-node-artifacts:
  stage: publish
  needs: ["docker-build"]
  script:
      - mkdir -p iep-node-artifacts/build
#      - cp build/iep-node.zip iep-node-artifacts/build
      - mkdir -p iep-node-artifacts/src/main/resources
      - cp src/main/resources/system.properties iep-node-artifacts/src/main/resources
      - cp src/main/resources/log4j2.xml iep-node-artifacts/src/main/resources
      - mkdir -p iep-node-artifacts/conf
      - cp conf/mainnet.properties iep-node-artifacts/conf
      - cp conf/testnet.properties iep-node-artifacts/conf
      - cp conf/custom.properties iep-node-artifacts/conf
      - mkdir -p iep-node-artifacts/conf/templates
      - cp conf/templates/installer.properties iep-node-artifacts/conf/templates
      - cp CHANGELOG-*.md iep-node-artifacts
      - cp LICENSE.txt iep-node-artifacts
  artifacts:
    paths:
      - iep-node-artifacts

trigger-iep-node-installer:
  stage: publish
  needs: ["prepare-iep-node-artifacts"]
  trigger: infinity-economics/iep-node-installer